# Generated by Django 5.0.6 on 2024-05-28 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kadai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, verbose_name='年')),
                ('month', models.PositiveSmallIntegerField(blank=True, verbose_name='月')),
                ('words', models.TextField(blank=True, null=True, verbose_name='検索ワード')),
                ('search_at', models.DateTimeField(auto_now=True, verbose_name='検索日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Kadai',
            },
        ),
    ]
